### ISSUE TITLE
TypeError in serializer/model.py

### ISSUE THREAD

**Issue by mwhdc** [dudanov/pyftms#12]
Hello, I have been using your Home Assistant FTMS integration with a UREVO treadmill with great success and tried to add another fitness device today. It is a ChangYow SI3928 console attached to a Rogue Echo Bike 3.0. The device is discovered and added successfully, though I'm not sure if the integration is pulling the correct set of available training data.

When trying to process live data, however, the integration throws an error and the ESPHome proxy that was receiving the data disconnects, then reconnects and the sequence restarts. A sample HA log entry is below.

The issue seems to be related to pyftms so I am reporting it here instead of under the HA integration. Please let me know if I can provide any other information to help identify the cause.

```
2024-12-07 21:07:14.826 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed. (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1019, in _read_ready__data_received
    self._protocol.data_received(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aioesphomeapi/_frame_helper/plain_text.py", line 93, in aioesphomeapi._frame_helper.plain_text.APIPlaintextFrameHelper.data_received
  File "aioesphomeapi/connection.py", line 956, in aioesphomeapi.connection.APIConnection.process_packet
  File "aioesphomeapi/client_callbacks.py", line 88, in aioesphomeapi.client_callbacks.on_bluetooth_gatt_notify_data_response
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 673, in <lambda>
    lambda handle, data: callback(data),
                         ~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/client/backends/controller.py", line 230, in _on_machine_status
    status = MachineStatusModel._deserialize(bio)
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 141, in _deserialize
    return cls(**cls._deserialize_asdict(src))
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/models/common.py", line 97, in _deserialize_asdict
    code = cast(int, next(it)[1].deserialize(src))
                     ~~~~^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 112, in _iter_fields_serializers
    serializers = _get_model_serializers(cls)
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 98, in _get_model_serializers
    result[field.name] = _get_model_field_serializer(field)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 88, in _get_model_field_serializer
    return _get_serializer(type_)
  File "/usr/local/lib/python3.13/site-packages/pyftms/serializer/model.py", line 69, in _get_serializer
    if issubclass(type_, (int, float)):
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
2024-12-07 21:07:14.828 WARNING (MainThread) [aioesphomeapi.connection] esp-btproxy @ [IP address]: Connection error occurred: issubclass() arg 1 must be a class
```

**Comment by dudanov** [comment]
Hello. Thanks.
Fixed in [v0.4.2](https://github.com/dudanov/pyftms/releases/tag/v0.4.2).
